AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**.rb'
    - 'lib/**.rb'
    - 'test/**.rb'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'tmp/**/*'
    - 'config/routes.rb'
    - 'config/puma.rb'

Metrics/MethodLength:
  Max: 60

Style/ClassAndModuleChildren:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'test/**/*_test.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*_test.rb'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*_test.rb'

Lint/UselessAssignment:
  Exclude:
    - 'test/**/*_test.rb'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*_test.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'

Layout/HashAlignment:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'

Style/PercentLiteralDelimiters:
  Enabled: false

Style/Proc:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/EmptyElse:
  EnforcedStyle: empty

Style/RedundantSelf:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/EmptyElse:
  Enabled: false

