version: '3.4'

services:
  mysql:
    image: mysql:5.7.29
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: resizing_gem_test
      MYSQL_USER: resizing_gem
      MYSQL_PASSWORD: secret
