version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-node
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_APP_CONFIG: "./.bundle"
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          LANG: ja_JP.UTF8
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: resizing_gem_test
          MYSQL_USER: resizing_gem
          MYSQL_PASSWORD: secret
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          LANG: ja_JP.UTF8
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

    steps:
      - checkout
      - run:
          name: Which bundler?
          command: |
            bundle -v
            bundle config

      - restore_cache:
          keys:
            - v2-{{ .Environment.CACHE_KEY }}-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v2-{{ .Environment.CACHE_KEY }}-gem-cache-{{ arch }}-{{ .Branch }}
            - v2-{{ .Environment.CACHE_KEY }}-gem-cache

      - run:
          name: reinstall rake && bundle install
          command: |
            sudo gem install bundler
            sudo gem uninstall -x rake
            echo "install: --no-document" >> ~/.gemrc
              bundle check --path vendor/bundle || bundle install --path vendor/bundle --clean

      - save_cache:
          key: v2-{{ .Environment.CACHE_KEY }}-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: connectable MySQL?
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

      # - run:
      #     name: rubocop
      #     command: bundle exec rubocop --parallel
      # - run:
      #     name: brakeman
      #     command: bundle exec brakeman --no-exit-on-error -w 1 -z
      - run:
          command: bundle exec rake test
          when: always
      - store_test_results:
          path: test/reports

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
